//
//  HomeInteractor.swift
//  Test_Bank_iOS
//
//  Created by Abhishek D on 13/10/19.
//  Copyright (c) 2019 Abhishek D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getUserDetails(request: Home.GetAccountHolderDetails.Request)
    func getAccountStatementList(request: Home.GetAccountStatementList.Request)
    func logout()
}

protocol HomeDataStore
{
    //var name: String { get set }
    var userDetails: UserAccount! { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var userDetails: UserAccount!
    //var name: String = ""
    
    // MARK: Display User Account Info
    
    func getUserDetails(request: Home.GetAccountHolderDetails.Request)
    {
        worker = HomeWorker()
        worker?.doSomeWork()
        
        let response = Home.GetAccountHolderDetails.Response(userAccountDetails: userDetails)
        presenter?.presentUserDetails(response: response)
    }
    
    // MARK: Account Statement List
    
    func getAccountStatementList(request: Home.GetAccountStatementList.Request)
    {
        let statementListWorker = StatementListWorker()
        statementListWorker.getStatementList { (success, statementList, error) in
            
            if success {
                let response = Home.GetAccountStatementList.Response(success: success, accountStatement: statementList?.statementList)
                self.presenter?.presentAccountStatementList(response: response)
            }
        }
    }
    
    // MARK: Logout
    
    func logout() {
        presenter?.presentLogout()
    }
    
}
