//
//  HomeModels.swift
//  Test_Bank_iOS
//
//  Created by Abhishek D on 13/10/19.
//  Copyright (c) 2019 Abhishek D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum Home
{
    // MARK: Use cases
    
    enum GetAccountHolderDetails
    {
        struct Request
        {
        }
        struct Response
        {
            var userAccountDetails: UserAccount
        }
        struct ViewModel
        {
            let name: String
            let bankAccountInfo: String
            let balance: Double
        }
    }
    
    enum GetAccountStatementList
    {
        struct Request
        {
        }
        struct Response
        {
            var success: Bool
            var accountStatement: [StatementList]?
        }
        struct ViewModel
        {
            var success: Bool
            let statementList: [StatementList]?
            
            struct StatementList: Codable {
                let title: String
                let desc: String
                let date: String
                let value: Double
            }
        }
    }
}
