//
//  TestBankLoginRouter.swift
//  Test_Bank_iOS
//
//  Created by Abhishek D on 13/10/19.
//  Copyright (c) 2019 Abhishek D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TestBankLoginRoutingLogic
{
  func routeToHome(segue: UIStoryboardSegue?)
}

protocol TestBankLoginDataPassing
{
  var dataStore: TestBankLoginDataStore? { get }
}

class TestBankLoginRouter: NSObject, TestBankLoginRoutingLogic, TestBankLoginDataPassing
{
  weak var viewController: TestBankLoginViewController?
  var dataStore: TestBankLoginDataStore?
  
  // MARK: Routing
  
  func routeToHome(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
        let destinationVC = segue.destination as! HomeViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToHome(source: dataStore!, destination: &destinationDS)
    } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToHome(source: dataStore!, destination: &destinationDS)
        navigateToHome(source: viewController!, destination: destinationVC)
    }
  }

   //MARK: Navigation
  
  func navigateToHome(source: TestBankLoginViewController, destination: HomeViewController)
  {
    source.show(destination, sender: nil)
  }
  
   //MARK: Passing data
  
  func passDataToHome(source: TestBankLoginDataStore, destination: inout HomeDataStore)
  {
    //destination.name = source.name
  }
}
