//
//  TestBankLoginModels.swift
//  Test_Bank_iOS
//
//  Created by Abhishek D on 13/10/19.
//  Copyright (c) 2019 Abhishek D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

/**
 This class store all the models related to the controller. The Models class will be related to each component. It will be of type struct and mostly it will contain Request, Response, and ViewModel structs.
 
 Usage:
 - **Request** - Parameters that need to be sent to the API request.
 - **Response** - Intercepts the response from the API and stores the appropriate data.
 - **ViewModel** - Everything that you need to show to the UI is stored here.
 */
enum TestBankLogin
{
    /**
     This `enum` bind request of the login authetication information to call the network API and fetch response from the network API will bind in the viewModel to display in the UI.
     */
  enum Login
  {
    struct Request
    {
        var userID: String?
        var password: String?
    }
    struct Response
    {
        var success: Bool
        var loginResponse: LoginResponse
    }
    
    struct Error
    {
        var success: Bool
        var errorResponse: ErrorResponse
    }
    
    struct ViewModel
    {
        let success: Bool
        let loginResponse: LoginResponse
    }
    
    struct ErrorModel {
        let success: Bool
        let errorResponse: ErrorResponse
    }
    
  }
}
